name: Database GitHub Tracker

on:
  fork:
  watch:
    types: [started]

jobs:
  report_event:
    runs-on: ubuntu-latest
    steps:
      - name: Send Event to Supabase
        run: |
          curl -X POST "${{ secrets.SUPABASE_URL }}/rest/v1/github_events" \
          -H "apikey: ${{ secrets.SUPABASE_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{"event": "${{ github.event_name }}", "author": "${{ github.actor }}", "repostory": "${{ github.repository }}", "is_notified": false}'